;; Problem 12

;; The sequence of triangle numbers is generated by adding
;; the natural numbers. So the 7^(th) triangle number would
;; be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

;; Let us list the factors of the first seven triangle numbers:

;; 1: 1
;; 3: 1,3
;; 6: 1,2,3,6
;; 10: 1,2,5,10
;; 15: 1,3,5,15
;; 21: 1,3,7,21
;; 28: 1,2,4,7,14,28

;; We can see that 28 is the first triangle number to have
;; over five divisors.

;; What is the value of the first triangle number to have
;; over five hundred divisors?

(ns problem012
  (:use [utils :only (| ceiling)]))

(defn triangle-numbers
  ([] (triangle-numbers 1))
  ([n]
   (lazy-seq
     (cons (/ (* n (inc n)) 2)
	   (triangle-numbers (inc n))))))

(defn num-of-divisors [n]
  (let [n* (int (ceiling (Math/sqrt n)))]
    (loop [d (int 1), num 0]
      (cond (> d n*) num
	    (| n d)
	    (if (= d n*)
	      (recur (inc d) (inc num))
	      (recur (inc d) (+ num 2)))
	    :else (recur (inc d) num)))))

(defn solve []
  (loop [[t & ts] (triangle-numbers)]
    (or (and (> (num-of-divisors t) 500) t)
	(recur ts))))
