;; Problem 44

;; Pentagonal numbers are generated by the formula, P_(n)=n(3n−1)/2.
;; The first ten pentagonal numbers are:

;; 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

;; It can be seen that P_(4) + P_(7) = 22 + 70 = 92 = P_(8).
;; However, their difference, 70 − 22 = 48, is not pentagonal.

;; Find the pair of pentagonal numbers, P_(j) and P_(k), for which
;; their sum and difference is pentagonal and D = |P_(k) − P_(j)|
;; is minimised; what is the value of D?

(ns problem044)

(defn solve []
  nil)
